export default {
  Normal: {
    type: 'NORMAL',
    name: '',
    contrast: 1.0,
    saturation: 1.0,
    brightness: 0.0,
    range: 1.0,
  },
  L1: {
    type: 'CSB',
    name: 'Lit',
    contrast: 1.69,
    saturation: 1.01,
    brightness: 0.35,
    range: 1.0,
  },
  L2: {
    type: 'CSB',
    name: 'Chill',
    contrast: 2.03,
    saturation: 0.92,
    brightness: 0.44,
    range: 1.0,
  },
  L3: {
    type: 'CSB',
    contrast: 1.76,
    name: 'Vibe',
    saturation: 1.19,
    brightness: 0.36,
    range: 1.0,
  },
  L4: {
    type: 'CSB',
    name: 'Gucci',
    contrast: 1.45,
    saturation: 0.75,
    brightness: 0.22,
    range: 1.0,
  },
  L5: {
    type: 'CSB',
    name: 'Vacay',
    contrast: 1.88,
    saturation: 0.93,
    brightness: 0.38,
    range: 1.0,
  },
  L6: {
    type: 'CSB',
    name: 'Salty',
    contrast: 1.76,
    saturation: 0.93,
    brightness: 0.3,
    range: 1.0,
  },
  L7: {
    type: 'CSB',
    name: 'City Vibes',
    contrast: 1.66,
    saturation: 0.35,
    brightness: 0.3,
    range: 1.0,
  },
  GRAYSCALE: {
    type: 'GRAYSCALE',
    name: 'Iconic',
    range: 1.0,
  },
  SEPIA: {
    type: 'SEPIA',
    name: 'Vintage',
    range: 1.0,
  },
  MONOCHROME: {
    type: 'MONOCHROME',
    name: 'Chrome',
    range: 1.0,
  },
  L11: {
    type: 'CSB',
    name: 'Beach',
    contrast: 2.39,
    saturation: 1.04,
    brightness: 0.58,
    range: 1.0,
  },
  L12: {
    type: 'CSB',
    name: 'Peachy',
    contrast: 2.06,
    saturation: 0.6,
    brightness: 0.44,
    range: 1.0,
  },
  L13: {
    type: 'CSB',
    name: 'Dream',
    contrast: 0.95,
    saturation: 0.5,
    brightness: -0.1,
    range: 1.0,
  },
  L14: {
    type: 'CSB',
    name: 'Honeymoon',
    contrast: 2.06,
    saturation: 0.62,
    brightness: 0.43,
    range: 1.0,
  },
  L15: {
    type: 'CSB',
    name: 'Urban',
    contrast: 1.1,
    saturation: 1.06,
    brightness: 0.08,
    range: 1.0,
  },
  L16: {
    type: 'CSB',
    name: 'Oasis',
    contrast: 0.97,
    saturation: 0.34,
    brightness: 0.0,
    range: 1.0,
  },
  L17: {
    type: 'CSB',
    name: 'Slay',
    contrast: 0.99,
    saturation: 0.97,
    brightness: -0.1,
    range: 1.0,
  },
  L18: {
    type: 'CSB',
    name: 'Goals',
    contrast: 0.91,
    saturation: 0.3,
    brightness: -0.04,
    range: 1.0,
  },
  L19: {
    type: 'CSB',
    name: 'Influencer',
    contrast: 0.78,
    saturation: 0.95,
    brightness: -0.11,
    range: 1.0,
  },
  blur: {
    type: 'BLUR',
    name: 'On Tilt',
    range: 1.5,
  },
  beauty: {
    type: 'BEAUTY',
    name: 'NORMAL',
    range: 1.5,
  },
};


